apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kodekloudapp
  name: kodekloudapp
  namespace: 'default'
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kodekloudapp
  template:
    metadata:
      labels:
        run: kodekloudapp
    spec:
      containers:
      - name: simplewebapp
        image: megha22/simplewebapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80